### ISSUE TITLE
issue when registering and logging in

### ISSUE THREAD

**Issue by mohamleh** [DavePearcey/ValkyriesFall-Public#12]
I put my information to register a new account, and when I clicked on register it moved to a new page that says runtime error which also has a description and details to the error and when I tried to register again it said that the email address is already in use then I tried to log into the account and it moved to the same runtime error page.
I can take a screenshot of the error and attach it, but I don't know if it'd be safe privacy wise to put it here so, if you think it'd be safe I'll attach it, if not I'll email it to you.

P.S. I didn't receive any email saying that I've registered a new account.

**Comment by DavePearcey** [comment]
I see errors in the logs about the use of non base64 characters used in the password validation. 

Looks like i need to do a front-end validation check to make sure the password complies with the frameworks requirements. These requirements possibly changed in a recent upgrade of the system used.
Though a runtime error also suggests possibility of a timeout, which could mean server issues, network or your own internet, but am uncertain.

Emails won't be sent on registration, or for any other purpose, unless requested as I have not asked players for permission to do so and is illegal to send an unsolicited email in my country. The email address is required by the system to make an account, but is only ever used by me when someone has an issue with their account and they request for me to manually change a password. I'll only send it to the email address associated with the account. 

You also make a very valid point that I've been meaning to resolve as well. I should show a "soft" error page, rather than throwing the error. Something I've been meaning to do, but have been distracted by making new features for the game!

**Comment by mohamleh** [comment]
Is there a need for me to reset the password ?
I noticed on another issue you said that there's a daily cleanup script that happens at midnight, which is around the time I registered my account.
My internet connection may not be the best, but it is working fine and I'm assuming the server is in Europe which is where I normally connect to when playing on a server.
My username is Mohock , you can send me an email with details if you want me to reset the password or register a new account, if I've to.

**Comment by DavePearcey** [comment]
I have reset the password and emailed it to the address on the account. I hop this solves the issue for you!

**Comment by DavePearcey** [comment]
I have found the issue in code. There was differences in code and config when it came to password validation. Code required a minimum of 8 characters, but the configuration for the password validator required 10. So those with passwords 8 or 9 characters long would get an error when validating their login. This will be released as a hot fix today.
